name: Build and Push - NODE 10

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - master
    paths:
      - node10/**

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Base Image
      - name: Build the Docker Base image
        run: cd node10/node10 && docker build . --file Dockerfile --tag labordigital/docker-base-images:node10
      - name: Push the image
        run: docker push labordigital/docker-base-images:node10

      # Dev Image
      - name: Build the Docker Dev image
        run: cd node10/node10-dev && docker build . --file Dockerfile --tag labordigital/docker-base-images:node10-dev
      - name: Push the image
        run: docker push labordigital/docker-base-images:node10-dev
