name: Build and Push - PHP 70

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - master
    paths:
      - php70/**

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Base Image
      - name: Build the Docker Base image
        run: cd php70/php70 && docker build . --file Dockerfile --tag labordigital/docker-base-images:php70
      - name: Push the image
        run: docker push labordigital/docker-base-images:php70

      # Dev Image
      - name: Checkout ssl certs
        uses: actions/checkout@v2
        with:
          repository: labor-digital/ssl-certs
          path: php70/php70-dev/ssl
      - name: Build the Docker Dev image
        run: cd php70/php70-dev && docker build . --file Dockerfile --tag labordigital/docker-base-images:php70-dev
      - name: Push the image
        run: docker push labordigital/docker-base-images:php70-dev
